# AWS Credentials
aws_region:     "${vpc_region}"

# VPC Information
vpc_name:       "${vpc_name}"
vpc_cidr_block: "${vpc_cidr_block}"

# For Security Group Rule
my_ip_range:          "${vpc_access_from_ip_range}"

# Subnets
public_subnet_1_cidr:  "${vpc_public_subnet_1_cidr}"

# Shippable Params Res to store state
STATE_RES_NAME: "${STATE_RES_NAME}"
